<a href="https://colab.research.google.com/github/DeboraBee/-Avalia-o-cont-nua-Aula-060.-Estat-stica-para-Explora-o-de-dados./blob/main/(Avalia%C3%A7%C3%A3o_cont%C3%ADnua)_Aula_060_Estat%C3%ADstica_para_Explora%C3%A7%C3%A3o_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Instalação de bibliotecas

In [1]:
# Realize a instalação de bibliotecas neste parágrafo
!pip install pandas scipy ucimlrepo

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (1.16.3)
Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.13/dist-packages (from ucimlrepo) (2026.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

# Importação de bibliotecas

In [2]:
# Realize a importação de bibliotecas neste parágrafo
import pandas as pd
from ucimlrepo import fetch_ucirepo

# Leitura do arquivo

Utilize os dados disponíveis no repositório [Student Performance](https://archive.ics.uci.edu/dataset/320/student+performance) do UCI.

In [3]:
# Leia o arquivo neste parágrafo
student_performance = fetch_ucirepo(id=320)
df = student_performance.data.features

# Análise Univariada

Para os cálculos da **análise univariada** utilize a coluna `age`

## Medidas de Frequência

### Frequência absoluta

In [4]:
# Realize o cálculo neste parágrafo
freq_abs = df['age'].value_counts().sort_index()
freq_abs

age
15    112
16    177
17    179
18    140
19     32
20      6
21      2
22      1
Name: count, dtype: int64

### Frequência relativa

In [5]:
# Realize o cálculo neste parágrafo
freq_rel = df['age'].value_counts(normalize=True).sort_index()
freq_rel

age
15    0.172573
16    0.272727
17    0.275809
18    0.215716
19    0.049307
20    0.009245
21    0.003082
22    0.001541
Name: proportion, dtype: float64

### Frequência absoluta acumulada

In [7]:
# Realize o cálculo neste parágrafo
freq_abs_acum = freq_abs.cumsum()
freq_abs_acum

age
15    112
16    289
17    468
18    608
19    640
20    646
21    648
22    649
Name: count, dtype: int64

### Frequência relativa acumulada

In [8]:
# Realize o cálculo neste parágrafo
freq_rel_acum = freq_rel.cumsum()
freq_rel_acum

age
15    0.172573
16    0.445300
17    0.721109
18    0.936826
19    0.986133
20    0.995378
21    0.998459
22    1.000000
Name: proportion, dtype: float64

## Medidas de localidade

### Mediana

In [9]:
# Realize o cálculo neste parágrafo
df['age'].median()

17.0

### 1º Quartil

In [10]:
# Realize o cálculo neste parágrafo
df['age'].quantile(0.25)

np.float64(16.0)

### 3º Quartil

In [11]:
# Realize o cálculo neste parágrafo
df['age'].quantile(0.75)

np.float64(18.0)

### Moda

In [12]:
# Realize o cálculo neste parágrafo
df['age'].mode()

0    17
Name: age, dtype: int64

## Medidas de espalhamento

### Amplitude

In [13]:
# Realize o cálculo neste parágrafo
df['age'].max() - df['age'].min()

7

### Distância entre o 3º e o 1º quartil

In [14]:
# Realize o cálculo neste parágrafo
df['age'].quantile(0.75) - df['age'].quantile(0.25)

np.float64(2.0)

### Desvio médio absoluto

In [16]:
# Realize o cálculo neste parágrafo
(df['age'] - df['age'].mean()).abs().mean()

np.float64(1.007951073240567)

### Variância

In [17]:
# Realize o cálculo neste parágrafo
df['age'].var()

1.483859308718057

### Desvio-padrão

In [18]:
# Realize o cálculo neste parágrafo
df['age'].std()

1.2181376394800618

## Medidas de distribuição

### Obliquidade

In [19]:
# Realize o cálculo neste parágrafo
df['age'].skew()

np.float64(0.4167953798111204)

Explique o resultado neste parágrafo

### Curtose

In [20]:
# Realize o cálculo neste parágrafo
df['age'].kurtosis()

np.float64(0.07150858494933487)

Explique o resultado neste parágrafo

# Análise Multivariada

Para os cálculos da análise muiltivariada utilize os campos `studytime` e `failures`.

## Covariância

In [21]:
# Realize o cálculo neste parágrafo
df[['studytime', 'failures']].cov()

           studytime  failures
studytime   0.688086 -0.072555
failures   -0.072555  0.351928

Explique o resultado neste parágrafo

## Correlação linear

In [22]:
# Realize o cálculo neste parágrafo
df[['studytime', 'failures']].corr()

           studytime  failures
studytime   1.000000 -0.147441
failures   -0.147441  1.000000

Explique o resultado neste parágrafo